name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume/resumeBuilder.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: resume/resume_KashifAhmad.pdf

      - name: Commit changes
        run: |
          git config --global user.email "kash15if@yahoo.com"
          git config --global user.name "Kash15if"
          git add .
          git commit -m "Compiled .tex to .pdf"
          git push origin main